# Streamlit Cloud Secrets Configuration Template
# Copy this content to your Streamlit Cloud app's Secrets section
# (Settings -> Secrets tab in your Streamlit Cloud dashboard)

# REQUIRED: Your OpenAI API Key
OPENAI_API_KEY = "sk-your-actual-openai-api-key-here"

# REQUIRED: Your Anthropic Claude API Key  
ANTHROPIC_API_KEY = "sk-ant-your-actual-anthropic-api-key-here"

# OPTIONAL: Default OpenAI model
DEFAULT_MODEL = "gpt-4o-mini"

# OPTIONAL: Default audit type
DEFAULT_AUDIT_TYPE = "general"
